<a href="https://colab.research.google.com/github/pranshu20p/Drug-Recommendation-Engine-/blob/main/Copy_of_Tool_Kit_1_SVD_PCA_mapping2_33_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Let us have a data set of 5 observations and 3 dimension.

In [ ]:
from scipy.stats import norm
import numpy as np
from scipy.linalg import eig
from numpy import cov
from numpy import argsort
from numpy import var
#Sample 1000 points from a Gaussian distribution with mean 0 and standard deviation 1
y1 = norm.rvs(size=(1,1000))
#Sample 1000 points from a Gaussian distribution with mean 0 and standard deviation 2
y2 = 2*norm.rvs(size=(1,1000))
#Sample 1000 points from a Gaussian distribution with mean 0 and standard deviation 5
y3 = 5*norm.rvs(size=(1,1000))
print('Maximum variance across y variables: '+ str(max(var(y1),var(y2),var(y3))))
#Generate the x variables from the y variables
x1 = y1
x2 = (y2+y3)/np.sqrt(2)
x3 = (y2-y3)/np.sqrt(2)
# x1, x2, x3 contain the three dimesnions of data matrix X
X= np.concatenate((x1,x2,x3), axis=0)
print('Maximum variance across x variables: '+ str(max(var(x1),var(x2),var(x3))))
X
print(X.shape)
#This is r* d matrix 
Xbar=X.T
print(X)

Maximum variance across y variables: 26.60595518608139
Maximum variance across x variables: 15.276047757227843
(3, 1000)
[[-0.23123531 -0.91893057 -0.49538615 ... -0.70488393 -1.43173983
  -0.25734684]
 [-3.20257697  1.99290713  0.42507208 ... -5.74946466  5.41770501
   3.11062296]
 [ 0.10004085  2.40727642 -0.23860353 ...  6.54654349 -6.34394609
  -4.75378116]]


In [ ]:
print(np.cov(X))#Covariance Matrix 

[[  0.9042194    0.06318974  -0.02701748]
 [  0.06318974  15.2913391  -11.40954876]
 [ -0.02701748 -11.40954876  15.15473892]]


In [ ]:
def function(X,n):# Function is not to be graded-Just for checking
  import numpy as np
  from sklearn.decomposition import PCA
  pca2=PCA(n_components=n,svd_solver='auto',random_state=232)
  model1=pca2.fit(X)
  model1.components_#Principal Componets 
  projection = pca2.fit_transform(X)
  return projection 

In [ ]:
Y_CHECK=function(Xbar,1)#JUST FOR CHECKING 

#WITHOUT USING ANY LIBRARY 

In [ ]:
#Now column vector of V represents represents Eigen vecotrs 

# Hence we can say:

data=np.dot(normalizedX,vt.T) # this multiploesAik*Bkj ie rows of A multiplied by Eigen Vector 1 which is Column  


In [ ]:

P=X
print(P)# EVERY ROW BECOMES A vector and column becomes observations 
P# Represents 3 dimensions and measurements /observations are columns

def Normalized (P):
 X_mean=np.mean(P,axis=1)
 z=np.zeros([P.shape[0],P.shape[1]])
 for i in  range(P.shape[1]):
    z[:,i]=np.subtract(P[:,i],X_mean)
 return z

Norm_mat=Normalized(P)

def SVD_PCA_DN(P):
   u,sigma,v=np.linalg.svd(Norm_mat)
   ubar=u[:,0]# represents singular or the first principal component 
#Hence we can say:
   Z=np.dot(ubar.T,Norm_mat)
   Z
   return Z,ubar

m,n=SVD_PCA_DN(P)
# EACH COLUMN IS OBSERVATION 


[[-0.23123531 -0.91893057 -0.49538615 ... -0.70488393 -1.43173983
  -0.25734684]
 [-3.20257697  1.99290713  0.42507208 ... -5.74946466  5.41770501
   3.11062296]
 [ 0.10004085  2.40727642 -0.23860353 ...  6.54654349 -6.34394609
  -4.75378116]]


In [ ]:
print(m)# Final Projection on all Principal Components 
variance=np.var(m)
print(variance,"variance of Projected data")

[ -2.28336064  -0.22688942   0.52752278   3.30074793   2.47689091
   1.46576416  -1.51674995   1.29619331  -1.33278513  -2.39122675
   8.05388871  -3.60843507  -2.76356873   4.42435593   0.24535135
  -3.97625813   4.65883509  -3.30136326   5.64841292  -7.57701794
   1.50590152  -3.89823302   6.20611342   8.59693047  -2.27774162
  -2.88005404   1.17692508  -4.3970666    4.95160644  -6.78958403
  -6.57563699  -1.46930624   1.95611004  -0.89306452  -1.94126934
  -8.6249732   -9.40772882  -1.92036499  -7.16117714  -3.1695875
  -4.48836845  -2.14166103  -5.74775853   6.25851957   5.31481822
  -4.25563703   3.07576469  -0.28984753   3.84347442  -1.16956525
  -8.57780783   7.45802123   1.01936859   1.68181522  -7.82433291
 -15.40691391   6.45411046  -0.76565898   0.78913256   2.43071086
   8.52855433  -2.44948354   3.19002927  -6.73204499  -1.88281775
  -1.36169128  -1.865337    -3.08775885  -3.68977282   2.48159827
   5.30459726   4.39090981  -2.67046656   1.04656172   1.16745994
   6.426661

1. I expect that the variance of data is higher than at least one of the features dimensions if reasonable information is carried by Principal Component. In this case we have 3 components so i expect that first component should have variance equal to or higher than atleast one components. 

2.. Variance of Projected  data represents how much of information is carried by the first Principal component. This means that we can say the first component is bent towards that feature. Hence we can say the new principal component is at a very close angle (cosine similar) to y axis. It is well possible that one principal component can represent most of the information/variance.

In [ ]:
#Projection matrix on First component 
n#where each column  vector is eigen vector . Hence we need to transpose it to call it a projection matrix 
Projection_Mat=n.T# Every  row is not e
Projection_Mat

array([ 0.00248214,  0.7092198 , -0.70498306])

$$/Sigma{x}$$